### PR TITLE
Newtonsoft.Json.Converters.StringEnumConverter Error Fix

### PR DESCRIPTION
**Pull request by deathbull**
Mentioned at https://github.com/jchristn/WatsonTcp/issues/154

### CODE REVIEW

**Comment by jchristn** [comment]
Hi @deathbull - does this resolve the issue for you?  I'm thinking that, if it does, instead of having a fixup method that the consumer must invoke, I could implement this inside the constructor of the client and server themselves.  Thoughts?

**Comment by deathbull** [comment]
it absolutely fixed the issue for me you can be sure

**Comment by jchristn** [comment]
I just integrated this (in a different way) and pushed into NuGet v4.8.14.3, could you give it a try?

NuGet: https://www.nuget.org/packages/WatsonTcp/4.8.14.3
Commit: https://github.com/jchristn/WatsonTcp/commit/f0883d73775488c8e7030673486e12511c3c6154

It's different in that I'm calling the ```Activator.CreateInstance``` directly from the constructor of both the client and server, so you don't have to in your code.  Also added you to the ```README```.  Thanks and let me know!

**Comment by deathbull** [comment]
yeah works well thanks

**Pull request closed without merging**
