### PR TITLE
Custom client metadata

### PR DESCRIPTION
**Pull request by developervariety**
Adds functionality for custom client metadata.

In my case since I sell a paid product w/o this functionality I need another list to contain licensed clients inside of so w/ this it'll keep all clients in one list and adds extensibility for anything else.

### CODE REVIEW

**Comment by jchristn** [comment]
Hi @developervariety how is the metadata then accessed after it's set?  I'm not seeing how this would be used within the library and generally assume that this kind of functionality would live outside of the library.  Thanks, Joel

**Comment by developervariety** [comment]
I completely forgot that `ClientMetadata` is not exposed when events are fired (MessageReceived etc.) so this makes the PR useless unless I add another method fetching the `ClientMetadata` based on `IpPort`..

What do you personally think?

**Comment by jchristn** [comment]
Hi Justin, I'm conflicted on it.  

On one hand, I expose a dictionary that allows consumers to set headers attached to messages.  It's also not used by the library.

This is very similar.  It seems like this would be the only reason to expose a portion of the ClientMetadata to the outside world.  I'll take some time to think this through.  I also have to weigh the fact that *it adds value to you and your app*. :)

Cheers, Joel

**Comment by developervariety** [comment]
I thought about it more, and honestly this functionality should stay out of the library like you said.

Thank you!

**Pull request closed without merging**
